### ISSUE TITLE
proofPurpose seems unnecessary in Controller Document spec

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#12]
`proofPurpose` was added to this specification by PR #11, but it seems unnecessary.  It wasn't in the original draft based on VC-DATA-INTEGRITY's Controller Document text and it's also not in VC-JOSE-COSE's Controller Document text.

It's the job of Data Integrity to define what's in a DI `proof` - not this specification.  We should therefore remove `proofPurpose` from this specification.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section3-5) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. proofPurpose seems unnecessary in Controller Document spec (issue controller-document#12)

_See github issue [controller-document#12](https://github.com/w3c/controller-document/issues/12)._




**Brent Zundel:** Proof purpose seems unnecessary in controller document spec. Proof purpose wasn't in the original data integrity spec or JOSE-COSE spec.  
… Is it possible that proof purpose was one of those properties where data integrity diverged from the controller document?  

**Manu Sporny:** Scanning the document. Proof purpose only shows up in three places, only in algorithm for creating the data integrity method.  
… Needs to be rewritten so that proof purpose doesn't come from data integrity.  

</details>

**Comment by selfissued** [comment]
This seems ready for a PR to remove `proofPurpose`.  Should I create it or would someone else like to?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-6) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.6. proofPurpose seems unnecessary in Controller Document spec (issue controller-document#12)

_See github issue [controller-document#12](https://github.com/w3c/controller-document/issues/12)._




**Brent Zundel:** moving on to #12, proof purpose seems unnecessary in controller document spec.  
… there seems to be a mismatch, what do folks think about this.  

**Manu Sporny:** I took this, it's ready for PR, I just need to raise the PR.  

</details>

**Comment by msporny** [comment]
PR #41 has been raised to address this issue. This issue will be closed once PR #41 has been merged.

**Comment by msporny** [comment]
PR #41 has been merged, closing.
