### ISSUE TITLE
X25519KeyAgreementKey2019 has wrong property

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/controller-document#34]
In the [example 15](https://w3c.github.io/vc-data-integrity/#example-key-agreement-property-containing-two-verification-methods) the key property is multibase whereas the suite (which I can't seem to find right now) says this should be base58. If this were X25519KeyAgreementKey2020 the multibase would make sense..

**Comment by selfissued** [comment]
Can anyone add a reference to the example in question in the Controller document spec and perhaps propose a wording change?  I couldn't find it after the issue was moved.

Or maybe https://github.com/w3c/controller-document/pull/39 already deals with this, in which case this can be closed?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-3) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. X25519KeyAgreementKey2019 has wrong property (issue controller-document#34)

_See github issue [controller-document#34](https://github.com/w3c/controller-document/issues/34)._




**Brent Zundel:** next up: issue 34.  

**Manu Sporny:** I assigned myself, will do this one and 35.  
… don't need group feedback for these editorial PRs.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-14-vcwg#section4-8) on 2024-08-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.8. X25519KeyAgreementKey2019 has wrong property (issue controller-document#34)

_See github issue [controller-document#34](https://github.com/w3c/controller-document/issues/34)._




**Manu Sporny:** No, Dave has the suggested change in here ... suggested in July 2023, so we just need to apply that fix.  

**Brent Zundel:** So this is just changing from using an X25519 key to a P-256 key.  
… Anyone else want to work on this?  

</details>

**Comment by msporny** [comment]
Fixed in commit b7409887d5bc4c97f0e5d59ff714558cfa8f0a22, closing.
