### ISSUE TITLE
Define "valid"

### ISSUE THREAD

**Issue by jyasskin** [w3c/controller-document#35]
- [ ] https://w3c.github.io/vc-data-integrity/#retrieve-verification-method says "If controllerDocument is not a valid [controller document](https://w3c.github.io/vc-data-integrity/#dfn-controller-documents), an error MUST be raised", but the link for "controller document" doesn't give an algorithm for determining whether a document is valid.
- [ ] It also says "If verificationMethod is not a valid [verification method](https://w3c.github.io/vc-data-integrity/#dfn-verification-method)" without an algorithm for identifying valid verification methods.

**Comment by selfissued** [comment]
I suggest changing "If controllerDocument is not a valid [controller document](https://w3c.github.io/controller-document/#dfn-controller-document)" to "If controllerDocument does not conform to the requirements defined by this specification".

Likewise, I suggest changing "If verificationMethod is not a valid [verification method](https://w3c.github.io/vc-data-integrity/#dfn-verification-method)" to "If verificationMethod does not conform to the requirements defined by this specification".

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-14-vcwg#section4-6) on 2024-08-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.6. Define "valid" (issue controller-document#35)

_See github issue [controller-document#35](https://github.com/w3c/controller-document/issues/35)._




> *Manu Sporny:* [https://w3c.github.io/controller-document/#conformance](https://w3c.github.io/controller-document/#conformance).

**Manu Sporny:** Right, agreed with what you said, Brent, I think we already have this in the spec. We have a conformance section -- talks about conforming document, processor, etc. There may be some detail that I'm missing in some comment.  

**Brent Zundel:** Would the fix then just be to fix the data integrity language to say "conforming"?  

> *Joe Andrieu:* +1 to say "conforming".

**Manu Sporny:** Yes.  
… I moved this over to the controller document spec because the retrieve verification method algorithm is now in the controller document spec. The change needs to be made there now.  
… What we should do is say "If the verification method is not a conforming verification method..." that will make it clear.  
… What Mike said in here is correct. We can make this more clear, it's an editorial change, I think it's ready for PR. We just need to link to the conforming statements and make this really clear.  

**Brent Zundel:** This is another one that is editorial and it's clear what to do so if they can help out Manu, that would be great.  

**Will Abramson:** I can do this one.  

</details>

**Comment by msporny** [comment]
PR #44 has been merged, closing.
