### ISSUE TITLE
Sections marked informative should be normative

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#46]
The [Introduction](https://www.w3.org/TR/2024/WD-controller-document-20240817/#introduction) and [Terminology](https://www.w3.org/TR/2024/WD-controller-document-20240817/#terminology) sections are current marked informative whereas the content of both are normatively required to successfully implement the specification.

Here are the comments from [my spec review](https://lists.w3.org/Archives/Public/public-vc-wg/2024Aug/0018.html) about this:

https://www.w3.org/TR/2024/WD-controller-document-20240817/#introduction
This section should be normative, since it contains a testable normative statement using RFC 2119 language.

https://www.w3.org/TR/2024/WD-controller-document-20240817/#terminology
This section should be normative, since applying the definitions of the terms is necessary to correctly implement the specification.

**Comment by msporny** [comment]
We should remove the SHOULD statement from the introduction, that's a holdover from another non-introductory portion.

Making the terminology section normative when there are zero RFC 2119 words in it isn't useful, they won't translate to tests in any test suite.

I'll raise a PR for the first change.

**Comment by selfissued** [comment]
Declarative sentences not marked non-normative in a specification are normative, whether they use RFC 2119 keywords or not.

If we're failing to test normative statements made not containing RFC 2119 keywords, that's a defect in our testing methodology.

**Comment by jyasskin** [comment]
Definitions often wind up determining parts of a test suite, even if you wouldn't write a test specifically for a definition. For example, in testing "Any verification methods contained in the controller documents for those identifiers SHOULD be accepted as authoritative, such that proofs that satisfy those verification methods are considered equivalent to proofs provided by the subject.", it's important for the test to rely on the fact that the "subject" is the entity named by the `id` of the top-level map in the controller document. If that definition changed, the test would also need to change.

**Comment by selfissued** [comment]
Based on @jyasskin's input, I believe this is ready for a PR.

**Comment by msporny** [comment]
PR #84 has been raised to address this issue. This issue will be closed once PR #84 has been merged.

**Comment by msporny** [comment]
> Declarative sentences not marked non-normative in a specification are normative, whether they use RFC 2119 keywords or not.

While that's true in theory, in practice, we don't depend on that sort of language in any of our specifications. We don't depend on declarative sentences because they've historically (over 10 years) been the source of endless debate on whether a test is needed for a declarative statement not including a normative keyword or not. To make things simple, both for readers and for implementers and test suite authors, we only implement tests for MUST statements. This makes it very clear to implementers what they need to do for conformance. If someone feels like a declarative sentence needs a test, we explicitly add a MUST to it.

> If we're failing to test normative statements made not containing RFC 2119 keywords, that's a defect in our testing methodology.

No, it's a design style that has been working well for us for well over a decade.

> Definitions often wind up determining parts of a test suite, even if you wouldn't write a test specifically for a definition. 

This is not true for our test suites for the reasons I elaborate upon above. In fact, we've found this sort of normative language vagueness to be an anti-pattern in test suites.

> If that definition changed, the test would also need to change.

No, it's debatable that the test would need to change because it's not clear what the normative parts of the statement are. Don't get me wrong, I get the theoretical argument that both you and @selfissued are making, I just reject it based on our experience writing precise test suites. When you don't use RFC 2119 keywords w/ BCP 14 applied in a specification for something you absolutely want tested, you're asking for trouble, it's vague and implementers will argue about the statement. Best to be explicit about exactly what you want tested and not depend on indirection to terminology, which is often clear in its intent, but can be vague when it comes to testing unless the normative guidance is far more specific.

While this is not a hill I'm willing to die on, we've been silently making the terminology sections in our other specifications normative because of this feedback, not because we all agree with it, but because making the section normative and making no changes to the test suite is easier than debating the topic. That said, we should probably stop doing that and address the core problem, which is the presumption that a terminology section with no RFC119 keywords but marked as normative has the effect on test suites that is being asserted. I don't think it does, so we might want to just push back on this entire concept of normative terminology sections. We can have that debate either here, or in the PR.

**Comment by selfissued** [comment]
@msporny, your comment about mixes two things:  Testing methodology and factual statements about what's normative.

This issue isn't about changing our testing methodology.  We can continue on only writing tests for MUSTs if we choose.

This is about it not being factually correct for the spec to say that the terminology is not normative when it is.  That's what we need to correct.

**Comment by msporny** [comment]
Based on discussion during the previous call, consensus in the group is to make the section normative, PR #91 has been raised to do that, this issue will be closed once PR #91 has been merged.

**Comment by msporny** [comment]
PR #84 has been merged (to address the normative language in the Introduction).

PR #91 ended up having merge conflicts, and the change of the Terminology section to normative was made in commit 568f38706f24973402a2fc72cb1c5263a3213b1e.

Those two actions address this issue, closing.
