### ISSUE TITLE
Cryptographic suite definition currently focuses on specifications rather than functionality

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#49]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#terminology
In the "cryptographic suite" definition, I suggest changing "A specification defining how to use" to "A means of using".  It being in a specification is superfluous.  Also, there may be multiple cryptographic suites defined in a single specification.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section4-4) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.4. Cryptographic suite definition currently focuses on specifications rather than functionality (issue controller-document#49)

_See github issue [controller-document#49](https://github.com/w3c/controller-document/issues/49)._




**Brent Zundel:** the goal of the issue conversation is to determine - is it triaged correctly, is someone assigned, do they need anything.  
… I'm gonna jump ahead and say - for most of these that are assigned, folks know what needs to be done.  
… we'll begin with number 49.  
… this is labeled as 'Editorial, ready for PR'.  
… which indicates that fix should be straightforward. does anyone disagree with the labeling?  
… also, need volunteer.  

**Michael Jones:** I'll do it.  

</details>
