### ISSUE TITLE
Put publicKeyJwk on an equal footing with publicKeyMultibase

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#5]
Most the of examples currently use `publicKeyMultibase` rather than `publicKeyJwk`.  I'm fine keeping most of those, but either equivalent `publicKeyJwk` representations should be added to those examples or parallel separate examples using `publicKeyJwk` should be added.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section3-3) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Put publicKeyJwk on an equal footing with publicKeyMultibase (issue controller-document#5)

_See github issue [controller-document#5](https://github.com/w3c/controller-document/issues/5)._




**Brent Zundel:** Start with 5.  
… Put public key JWK on same footing as public key multibase.  
… Suggested move forward is to adjust the examples.  

**Manu Sporny:** Fine to add examples.  

**Brent Zundel:** Fine to let this sit for now.  
… On to 9.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-2) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.2. Put publicKeyJwk on an equal footing with publicKeyMultibase (issue controller-document#5)

_See github issue [controller-document#5](https://github.com/w3c/controller-document/issues/5)._




**Brent Zundel:** next #5. Mike not able to join us today.  
… most examples using public key multibase not public key jwk, need both in examples.  
… is anyone opposed to doing this?  
… will anyone take on the task of doing this?  

**Manu Sporny:** I can get to it eventually but not immediately.  

**Brent Zundel:** decentralgabe you are another person well suited to address this.  

**Gabe Cohen:** yes you can assign me.  

**Brent Zundel:** if you want to interact with Mike and get him assigned as well that is fine.  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-14-vcwg#section4-7) on 2024-08-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.7. Put publicKeyJwk on an equal footing with publicKeyMultibase (issue controller-document#5)

_See github issue [controller-document#5](https://github.com/w3c/controller-document/issues/5)._




**Brent Zundel:** PR #39 will address this issue.  

</details>

**Comment by msporny** [comment]
PR #39 has been merged, closing.
