### ISSUE TITLE
Verification method definition wordy

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#50]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#terminology
In the "verification method" definition, I suggest changing "A set of parameters that can be used together with a process to independently verify a proof" to "A method of independently verifying a proof."  Keep it simple.

**Comment by msporny** [comment]
No, the parameters are important inputs to the process. People didn't understand that it was just an algorithm before, but an algorithm with parameters. "Keeping it simple" caused confusion before, which is why the text is the way it is now.

**Comment by selfissued** [comment]
What are the parameters being referred to?  If we're going to use that language, it needs to be understandable by readers what the parameters are.

BTW, I'd request that you stop marking issues "pending close" until they've been discussed by the working group.  Thank you.

**Comment by msporny** [comment]
> BTW, I'd request that you stop marking issues "pending close" until they've been discussed by the working group. Thank you.

I'm marking issues as "pending close" as an Editor of the specification that is triaging issues. There are 7 days to discuss/object and the WG won't close the issue until it's been discussed at least once in a WG call. Please stop unlabeling issues that have been triaged until the WG can determine if the triage is appropriate.

**Comment by msporny** [comment]
> What are the parameters being referred to? If we're going to use that language, it needs to be understandable by readers what the parameters are.

The parameters are all of the properties in a verification method... identifiers, controllers, cryptographic key values like `x` and `y`, etc.

**Comment by selfissued** [comment]
As a fellow editor, I'm eligible to participate in the triage process as well.  Therefore, when I believe that an issue needs working group discussion, it's reasonable for me to remove "pending close" labels.

**Comment by selfissued** [comment]
What about "A method and its parameters used to independently verify a proof"?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-04-vcwg#section2-8) on 2024-09-04

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.8. Verification method definition wordy (issue controller-document#50)

_See github issue [controller-document#50](https://github.com/w3c/controller-document/issues/50)._




**Brent Zundel:** verification method definition is wordy.  
… selfissued suggested new wording to make it simpler.  
… manu said it looses quality.  

**Manu Sporny:** selfissued has a suggestion at the very end that could work.  
… this does need a review as it changes text around a key term.  

**Brent Zundel:** sounds good.  
… we're going to take a break from controller document.  
… most of those PRs are going to be merged before we meet again.  

</details>

**Comment by msporny** [comment]
In order to make progress at W3C TPAC, I am suggesting that this issue is "editorial" and can be resolved during the Candidate Recommendation phase. The VCWG will discuss this issue at W3C TPAC to see if the "during CR" determination is correct.

**Comment by msporny** [comment]
PR #121 has been raised to address this issue. This issue will be closed once PR #121 has been merged.

**Comment by msporny** [comment]
PR #121 has been merged, closing.
