### ISSUE TITLE
Add Controller Document examples to the Data Model section

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#51]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#data-model
The inline issue says "Add examples of common Controller documents."  I don't know that we can judge what is "common" or whether it's relevant.  Maybe just add some Controller Document examples here?

**Comment by selfissued** [comment]
Ideally, there should be an example not using JSON-LD and another example using it.

**Comment by selfissued** [comment]
This has become a duplicate of #72

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section4-5) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5.  (issue controller-document#51)

_See github issue [controller-document#51](https://github.com/w3c/controller-document/issues/51)._




**Brent Zundel:** another editorial, ready for pr labeled issue.  
… straightforward change suggested. need volunteer.  

**Manu Sporny:** this was raised by Orie, he just wanted an example.  

</details>
