### ISSUE TITLE
Add Definition Reference column to Controller Documents property table

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#53]
The fields in this new column should be hyperlinks to the definitions of the properties.

Here are the comments from [my spec review](https://lists.w3.org/Archives/Public/public-vc-wg/2024Aug/0018.html) about this:

https://www.w3.org/TR/2024/WD-controller-document-20240817/#controller-documents
The spec says "The property names in the tables are linked to the normative definitions and more detailed descriptions of each property" but this isn't the case.  "id", "alsoKnownAs", etc. in the table are not hyperlinks.

https://www.w3.org/TR/2024/WD-controller-document-20240817/#controller-documents
Many of the definitions in the table are not particularly useful.  For instance, "id" is defined as "A string that conforms to the URL syntax defined in Section 2.1.1 Subjects."  But no description is present of what an "id" is used for.  Oh, wait - the definition is at 2.1.1 but what the text says is that the URL syntax is defined in 2.1.1.  I suggest adding a fourth column titled "Definition Reference" and move all the section references to that column and out of the "Value Constraints" column.

**Comment by selfissued** [comment]
I agree that this is ready for a PR.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section4-6) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.6. Add Definition Reference column to Controller Documents property table (issue controller-document#53)

_See github issue [controller-document#53](https://github.com/w3c/controller-document/issues/53)._




**Brent Zundel:** same, editorial, ready for pr.  

**Manu Sporny:** I'll note we already have this in the spec, we link to the sections.  
… just to clarify - are you asking to just put those links in another column on the table?  

**Michael Jones:** yes.  

</details>

**Comment by msporny** [comment]
PR #85 has been raised to address this issue. This issue will be closed once PR #85 has been merged.

**Comment by msporny** [comment]
PR #85 has been merged, closing.
