### ISSUE TITLE
Authorization vs authentication note confusing

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#55]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#controllers
The note on "Authorization vs authentication" is confusing and not particularly actionable.  In particular, the meaning of phrase "authorization provided by the value of controller" is fairly inscrutable.  What is the "authorization provided" and to what?  This note needs to be reworked to be comprehensible and actionable or removed.

**Comment by selfissued** [comment]
I agree that this is ready for a PR.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section4-7) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.7. Authorization vs authentication note confusing (issue controller-document#55)

_See github issue [controller-document#55](https://github.com/w3c/controller-document/issues/55)._




**Brent Zundel:** same as before, editorial, ready for pr.  
… Mike makes a suggestion for some minor changes.  
… need volunteers.  

**Manu Sporny:** I can work on rewording.  

</details>

**Comment by msporny** [comment]
PR #86 has been raised to address this issue. This issue will be closed once PR #86 has been merged.

**Comment by msporny** [comment]
PR #86 has been merged, closing.
