### ISSUE TITLE
Verification method controller(s) and controller(s) note confusing

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#57]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#verification-methods
The note "Verification method controller(s) and controller(s)" is pretty opaque. To steal a phrase from the game Adventure, "You're in a twisty maze of words, all alike." The confusion evoked here is perhaps related to that described at https://github.com/w3c/controller-document/pull/42#discussion_r1721008946 ?  This needs to be much clearer.

**Comment by selfissued** [comment]
I agree that this is ready for a PR.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section4-9) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.9. Verification method controller(s) and controller(s) note confusing (issue controller-document#57)

_See github issue [controller-document#57](https://github.com/w3c/controller-document/issues/57)._




**Michael Jones:** a meta point, if manu believes it's ready for PR, and I believe it's ready for PR, I'd like authorization from the WG for the two editors to collaborate & create PRs.  

**Brent Zundel:** absolutely, that'd be fantastic.  

**Ted Thibodeau Jr.:** to be clear, those are PRs that are then open for comments, yes?  

**Brent Zundel:** yes, of course.  

---

</details>

**Comment by msporny** [comment]
PR #87 has been raised to address this issue. This issue will be closed once PR #87 has been merged.

**Comment by msporny** [comment]
PR #87 has been merged, closing.
