### ISSUE TITLE
Delete unnecessary repetition of content defined elsewhere

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#67]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#contexts-and-vocabularies
The text in Section 4 (Context and Vocabularies) reiterates content defined elsewhere - hashes of contexts - that is not needed for Controller Documents.  Even when the controller document uses JSON-LD, which is optional, this at-risk content can be obtained from its primary sources.  Please delete this heading and all the text before Section 4.1.

**Comment by iherman** [comment]
This issue should be closed if and when #68 is merged.

**Comment by msporny** [comment]
The content is defined in the Data Integrity specification. While I'd be happy to put a normative definition to that specification in the controller document specification, others would object. It's there because we tried it the other way and people objected.

**Comment by msporny** [comment]
@iherman #68 is an issue, did you mean #43?

**Comment by selfissued** [comment]
Let's discuss this in the working group.

**Comment by selfissued** [comment]
At the very least, this content should move to the Data Integrity spec:

> URL: https://w3id.org/security/data-integrity/v2 (application/ld+json)
> SHA2-256 Digest: 67f21e6e33a6c14e5ccfd2fc7865f7474fb71a04af7e94136cb399dfac8ae8f4

**Comment by msporny** [comment]
> At the very least, this content should move to the Data Integrity spec

That content already exists in the Data Integrity specification, as described here:

https://github.com/w3c/vc-data-integrity/issues/308#issuecomment-2351829685

**Comment by selfissued** [comment]
Closing, since this was removed from the spec:
> URL: https://w3id.org/security/data-integrity/v2 (application/ld+json)
SHA2-256 Digest: 67f21e6e33a6c14e5ccfd2fc7865f7474fb71a04af7e94136cb399dfac8ae8f4

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-27-vcwg#section3-7) on 2024-09-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7.  (issue controller-document#67)

_See github issue [controller-document#67](https://github.com/w3c/controller-document/issues/67)._




**Manu Sporny:** We had duplicate content on the spec between Data Integrity and controller document. Ivan raised a PR to remove the content that was merged. selfissued suggested that we move a line from the controller document to the Data Integrity spec, but that text already exists in the DI spec, so that's why I have marked it pending close.  

**Brent Zundel:** selfissued, we believe we have addressed your concern, need your feedback.  

**Michael Jones:** so we did delete the hash of the data integrity URL, if that is the case I will agree to close this.  

**Brent Zundel:** that was the only issue marked as not during CR, except another one, role of the subject.  

</details>
