### ISSUE TITLE
Make Conformance Classes a top-level section

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#7]
Conformance Classes currently appears as a subsection in the Introduction section.  That seems far too early in the document for readers to have any context to be able to understand it.

I suggest moving it to its own top-level section late in the document, as was done in VC-JOSE-COSE.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section3-6) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.6. Make Conformance Classes a top-level section (issue controller-document#7)

_See github issue [controller-document#7](https://github.com/w3c/controller-document/issues/7)._




**Brent Zundel:** On to 7.  
… Conformance classes appears too early in the document. Move to late in the document.  
… We had a conversation about this last month. JOSE-COSE is the only document that does it this way, controller document more closely aligns with other documents produced. No agreement that this should be done.  
… We don't have consensus that this issue should be addressed.  

**Manu Sporny:** Objects to moving this to somewhere else. In ReSpec, conformance section has boilerplate and top has "How to read this document".  
… Standard boilerplate goes at the top of every W3C specification. Good for people to read that bit.  
… Moving in document doesn't appear to make it better than what we have right now.  
… Have this setup in multiple specifications, no object until now.  

**Brent Zundel:** On to 18.  

</details>

**Comment by msporny** [comment]
The group has discussed this twice and there is no support to make the conformance section a top level section. Our specifications have contained conformance sections in the introductory portion of the specifications for years now and there does not seem to be a desire to change that. Marking as pending close.

**Comment by selfissued** [comment]
VC-JOSE-COSE has this as a top-level section, so there's precedent in the WG for doing it this way.  It's more logical and reads more easily, since you're not giving the reader information before they have the context to understand it.

**Comment by jandrieu** [comment]
+1 for a consistent spec structure. I'd suggest we bring JOSE-COSE in sync with the structure we've used for the rest of the work.

**Comment by TallTed** [comment]
I submit that VC-JOSE-COSE is the odd man out, and should be revised to match the other documents produced by this working group.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-5) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. Make Conformance Classes a top-level section (issue controller-document#7)

_See github issue [controller-document#7](https://github.com/w3c/controller-document/issues/7)._




**Brent Zundel:** next up #7, make conformance classes a top level section.  
… manu this is assigned to you - conversation needed for the group?  

**Manu Sporny:** on 6/30 I reported that the group has discussed this twice, no support to make this change, following same approach as in other specs, I marked this issue pending close, Mike disagreed and removed the label, I don't think anything has changed and we are not expecting to make this change, group should make decision so we can close the issue.  
… proposal: do not make conformance classes a top level section to conform with other specs.  

**Ted Thibodeau Jr.:** +1 manu, perhaps we should push back on Mike to change Jose-cose to conform with the rest of the specs created by this WG.  

> *Manu Sporny:* +1 to TallTed's suggestion that VC-JOSE-COSE should follow what all the other specs do.

**Brent Zundel:** not hearing any pushback on Manu's proposal, going to marked this issue closed.  

> *Phillip Long:* +1 to Manu's request to close issue #7.

> *Gabe Cohen:* opened [https://github.com/w3c/vc-jose-cose/issues/284](https://github.com/w3c/vc-jose-cose/issues/284).

</details>

**Comment by msporny** [comment]
Closing issue per discussion on 2024-07-31 telecon.
