### ISSUE TITLE
Condense Accessibility Considerations section

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#8]
I suggest revising the Accessibility Considerations section to say that the specification specifies has no user interface elements and therefore there are no accessibility considerations.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-05-15-vcwg#section3-3) on 2024-05-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Condense Accessibility Considerations section (issue vc-controller-document#8)

_See github issue [vc-controller-document#8](https://github.com/w3c/vc-controller-document/issues/8)._




**Michael Jones:** This spec doesn't display them. We should cut it down to what is needed. If there are new UI considerations we shouldn't introduce this an accessibility issue.  

---


</details>

**Comment by iherman** [comment]
I have a practical reason for not being in favor of doing this.

We are under extreme time pressure with this spec. One hurdle will be to get through the horizontal review.

At this moment, we can issue these review requests by, essentially, saying that the document does not do anything new. It just takes texts in current CR-s, _**texts that have already been gone through the horizontal reviews**_, and therefore doing a review on this specification is not really necessary. As soon as we begin editorializing the text, we lose this argument, we have to ask for a genuine review, and we lose time.

I think I agree with your argument, @selfissued. But, in this case, I do not think we have the luxury of changing things.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section3-5) on 2024-06-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. Condense Accessibility Considerations section (issue controller-document#8)

_See github issue [controller-document#8](https://github.com/w3c/controller-document/issues/8)._




> *Manu Sporny:* Yes, +1, agree with what brent just said... applying Mike's change would change the horizontal review assertions (that they've reviewed and approved a variation of this before).

**Brent Zundel:** because we are pulling text from existing documents, we should not in this case re-write to make text cleaner, but rather keep as is.  

> *Dave Longley:* +1.

**Brent Zundel:** since this will make horizontal reviews much easier.  

</details>

**Comment by msporny** [comment]
The group discussed this during the last call and decided to not change the Accessibility Considerations section because it would needlessly trigger another more in depth accessibility review.
