### ISSUE TITLE
Review sections marked non-normative

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#9]
Far more sections are marked "non-normative" in this specification than in some of our other specifications.  I believe we should review them to determine whether they contain any normatively useful material, and if so, remove the "non-normative" designation.

**Comment by msporny** [comment]
I reviewed the document. The only non-normative sections are the Introduction, security/privacy/a11y considerations, and examples sections (and rest of the appendix). Everything else is normative, which seems to be correct. I think the spec is fine as-is. Other reviews would be good to double check.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section3-4) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Review sections marked non-normative (issue controller-document#9)

_See github issue [controller-document#9](https://github.com/w3c/controller-document/issues/9)._




**Brent Zundel:** Far more sections are marked non-normative than other spec. This is an encouragement to review to ensure that they are indeed non-normative.  

**Manu Sporny:** Believes that ReSpec will complain if there is a normative statement in a non-normative section.  

**Brent Zundel:** Agrees that tooling should be of assistance.  
… Task here is to read through the spec and to make adjustments.  

**Manu Sporny:** Scanning the entire document. Only non-normative section is the introduction. Everything else normative until security and privacy considerations. Believes that issue is not correct.  
… Disagrees that there are more non-normative sections than other specs. Follows the pattern for others.  
… Examples are supposed to be non-normative. Cursory review says everything is fine.  

**Brent Zundel:** Additional reviewers would be valuable.  

> *KevinDean:* On to 12.

**Brent Zundel:** On to 12.  

</details>

**Comment by msporny** [comment]
A review of the specification wrt. sections marked non-normative has been done. No anomaly's have been detected. The group was also asked to review in case others had other opinions. Marking as pending close.
